### ISSUE TITLE
get methods

### ISSUE THREAD

**Issue by mr-tron** [pyAndr3w/ton-preprocessed-wallet-v2#10]
at least get_seqno because parsing data is haram.
also in case of code updating get methods help to keep backward compatibility

**Comment by cryshado** [comment]
Hello @mr-tron,

I understand that you are suggesting to use the get_seqno method instead of parsing data, and that using get methods can help maintain backward compatibility when updating code. However, I would like to ask you to use more respectful language in your statements.

Regarding the smart contract development, we have chosen a way to make the wallet as gas-efficient as possible while maintaining security, and adding get methods would increase its cost. Instead, we have provided a debot with the smart contract, which allows users to interact with it without directly accessing the cells. This provides a convenient and secure way to use the smart contract.

I close this issue.
